/** \file resource.h
 * \brief Resources for localization
 * 
 * \author Yuji DOI<yuji5296@gmail.com>
 * \date 2008-2009
 */
#ifndef resource_h
#define resource_h
#define EC_MONTH01_AM	"መስከረም"
#define EC_MONTH02_AM	"ጥቅምት"
#define EC_MONTH03_AM	"ኀዳር"
#define EC_MONTH04_AM	"ታኀሳስ"
#define EC_MONTH05_AM	"ጥር"
#define EC_MONTH06_AM	"የካቲት"
#define EC_MONTH07_AM	"መጋቢት"
#define EC_MONTH08_AM	"ሚያዝያ"
#define EC_MONTH09_AM	"ግንቦት"
#define EC_MONTH10_AM	"ሰኔ"
#define EC_MONTH11_AM	"ሐምሌ"
#define EC_MONTH12_AM	"ነሐሴ"
#define EC_MONTH13_AM	"ጳጉሜን"

#define EC_MONTH01	"Meskerem"
#define EC_MONTH02	"Tikimt"
#define EC_MONTH03	"Hidar"
#define EC_MONTH04	"Tahsas"
#define EC_MONTH05	"Tir"
#define EC_MONTH06	"Yakatit"
#define EC_MONTH07	"Megabit"
#define EC_MONTH08	"Miazia"
#define EC_MONTH09	"Ginbot"
#define EC_MONTH10	"Sene"
#define EC_MONTH11	"Hamle"
#define EC_MONTH12	"Nehase"
#define EC_MONTH13	"Pagumen"

#define EC_WEEKDAY0_AM "እሑ"
#define EC_WEEKDAY1_AM "ሰኞ"
#define EC_WEEKDAY2_AM "ማክ"
#define EC_WEEKDAY3_AM "ረቡ"
#define EC_WEEKDAY4_AM "ሐሙ"
#define EC_WEEKDAY5_AM "ዐር"
#define EC_WEEKDAY6_AM "ቅዳ"

#define EC_WEEKDAY0 "Ehud"
#define EC_WEEKDAY1 "Segno"
#define EC_WEEKDAY2 "Maksegno"
#define EC_WEEKDAY3 "Rebue"
#define EC_WEEKDAY4 "Hamus"
#define EC_WEEKDAY5 "Arb"
#define EC_WEEKDAY6 "Kidame"

#define GC_MONTH01	"January"
#define GC_MONTH02	"February"
#define GC_MONTH03	"March"
#define GC_MONTH04	"April"
#define GC_MONTH05	"May"
#define GC_MONTH06	"June"
#define GC_MONTH07	"July"
#define GC_MONTH08	"August"
#define GC_MONTH09	"September"
#define GC_MONTH10	"October"
#define GC_MONTH11	"November"
#define GC_MONTH12	"December"

#define GC_WEEKDAY0 "Sunday"
#define GC_WEEKDAY1 "Monday"
#define GC_WEEKDAY2 "Tuesday"
#define GC_WEEKDAY3 "Wednesday"
#define GC_WEEKDAY4 "Thursday"
#define GC_WEEKDAY5 "Friday"
#define GC_WEEKDAY6 "Saturday"

#define GC_WEEKDAY0_LABEL "Sun"
#define GC_WEEKDAY1_LABEL "Mon"
#define GC_WEEKDAY2_LABEL "Tue"
#define GC_WEEKDAY3_LABEL "Wed"
#define GC_WEEKDAY4_LABEL "Thu"
#define GC_WEEKDAY5_LABEL "Fri"
#define GC_WEEKDAY6_LABEL "Sat"

#define GC_WEEKDAY0_LABEL_JP "日"
#define GC_WEEKDAY1_LABEL_JP "月"
#define GC_WEEKDAY2_LABEL_JP "火"
#define GC_WEEKDAY3_LABEL_JP "水"
#define GC_WEEKDAY4_LABEL_JP "木"
#define GC_WEEKDAY5_LABEL_JP "金"
#define GC_WEEKDAY6_LABEL_JP "土"

#define IC_MONTH01	"Muharram"
#define IC_MONTH02	"Safar"
#define IC_MONTH03	"Rabi' al-awwal"
#define IC_MONTH04	"Rabi' al-thani"
#define IC_MONTH05	"Jumada al-awwal"
#define IC_MONTH06	"Jumada al-thani"
#define IC_MONTH07	"Rajab"
#define IC_MONTH08	"Sha'aban"
#define IC_MONTH09	"Ramadan"
#define IC_MONTH10	"Shawwal"
#define IC_MONTH11	"Dhu al-Qi'dah"
#define IC_MONTH12	"Dhu al-Hijjah"

#define IC_WEEKDAY0 "al-ahad"
#define IC_WEEKDAY1 "al-ithnayn"
#define IC_WEEKDAY2 "ath-thulaathaa"
#define IC_WEEKDAY3 "al-arbia`aa'"
#define IC_WEEKDAY4 "al-khamis"
#define IC_WEEKDAY5 "al-jumu`a"
#define IC_WEEKDAY6 "as-sabt"

#define IC_WEEKDAY0_LABEL "ahad"
#define IC_WEEKDAY1_LABEL "ithnayn"
#define IC_WEEKDAY2_LABEL "thulaathaa"
#define IC_WEEKDAY3_LABEL "arbia`aa'"
#define IC_WEEKDAY4_LABEL "khamis"
#define IC_WEEKDAY5_LABEL "jumu`a"
#define IC_WEEKDAY6_LABEL "sabt"

#endif
